/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(container)'}${'/(app)'}${'/(private)'}/portfolio-distribution` | `/portfolio-distribution`; params?: Router.UnknownInputParams; } | { pathname: `${'/(container)'}${'/(app)'}${'/(private)'}/view-portfolio` | `/view-portfolio`; params?: Router.UnknownInputParams; } | { pathname: `${'/(container)'}${'/(app)'}${'/(private)'}${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(container)'}${'/(app)'}${'/(private)'}${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(container)'}${'/(app)'}${'/(private)'}${'/(tabs)'}/transactions` | `/transactions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(container)'}${'/(app)'}${'/(private)'}${'/(tabs)'}/wallet` | `/wallet`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(container)'}${'/(app)'}${'/(private)'}/portfolio-distribution` | `/portfolio-distribution`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(container)'}${'/(app)'}${'/(private)'}/view-portfolio` | `/view-portfolio`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(container)'}${'/(app)'}${'/(private)'}${'/(tabs)'}/home` | `/home`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(container)'}${'/(app)'}${'/(private)'}${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(container)'}${'/(app)'}${'/(private)'}${'/(tabs)'}/transactions` | `/transactions`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(container)'}${'/(app)'}${'/(private)'}${'/(tabs)'}/wallet` | `/wallet`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(container)'}${'/(app)'}${'/(private)'}/portfolio-distribution${`?${string}` | `#${string}` | ''}` | `/portfolio-distribution${`?${string}` | `#${string}` | ''}` | `${'/(container)'}${'/(app)'}${'/(private)'}/view-portfolio${`?${string}` | `#${string}` | ''}` | `/view-portfolio${`?${string}` | `#${string}` | ''}` | `${'/(container)'}${'/(app)'}${'/(private)'}${'/(tabs)'}/home${`?${string}` | `#${string}` | ''}` | `/home${`?${string}` | `#${string}` | ''}` | `${'/(container)'}${'/(app)'}${'/(private)'}${'/(tabs)'}/profile${`?${string}` | `#${string}` | ''}` | `/profile${`?${string}` | `#${string}` | ''}` | `${'/(container)'}${'/(app)'}${'/(private)'}${'/(tabs)'}/transactions${`?${string}` | `#${string}` | ''}` | `/transactions${`?${string}` | `#${string}` | ''}` | `${'/(container)'}${'/(app)'}${'/(private)'}${'/(tabs)'}/wallet${`?${string}` | `#${string}` | ''}` | `/wallet${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(container)'}${'/(app)'}${'/(private)'}/portfolio-distribution` | `/portfolio-distribution`; params?: Router.UnknownInputParams; } | { pathname: `${'/(container)'}${'/(app)'}${'/(private)'}/view-portfolio` | `/view-portfolio`; params?: Router.UnknownInputParams; } | { pathname: `${'/(container)'}${'/(app)'}${'/(private)'}${'/(tabs)'}/home` | `/home`; params?: Router.UnknownInputParams; } | { pathname: `${'/(container)'}${'/(app)'}${'/(private)'}${'/(tabs)'}/profile` | `/profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(container)'}${'/(app)'}${'/(private)'}${'/(tabs)'}/transactions` | `/transactions`; params?: Router.UnknownInputParams; } | { pathname: `${'/(container)'}${'/(app)'}${'/(private)'}${'/(tabs)'}/wallet` | `/wallet`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
